version: '3.7'

services:

   test:
      build: ./postgres-11
      environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: acme
      ports:
         - 5432:5432
